<a href="https://colab.research.google.com/github/vvikasreddy/lexically_constrained_beam_search_/blob/main/beam_search.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## downloading essential modules

In [2]:
!pip install datasets

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 13.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 8.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 12.9 MB/s eta 0:00:00
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.10.0
    Uninstalling fsspec-2024.10.0:
      Successfully uninstalled fsspec-2024.10.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.


In [3]:
# Using the cs-en translation

In [4]:
from datasets import load_dataset

import torch
from transformers import MarianMTModel, MarianTokenizer



In [5]:
ds = load_dataset("wmt/wmt16", "tr-en")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


README.md:   0%|          | 0.00/11.1k [00:00<?, ?B/s]

train-00000-of-00001.parquet:   0%|          | 0.00/36.8M [00:00<?, ?B/s]

validation-00000-of-00001.parquet:   0%|          | 0.00/153k [00:00<?, ?B/s]

test-00000-of-00001.parquet:   0%|          | 0.00/466k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/205756 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1001 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/3000 [00:00<?, ? examples/s]

In [6]:
ds

DatasetDict({
    train: Dataset({
        features: ['translation'],
        num_rows: 205756
    })
    validation: Dataset({
        features: ['translation'],
        num_rows: 1001
    })
    test: Dataset({
        features: ['translation'],
        num_rows: 3000
    })
})

In [7]:
ds['train'][0]

{'translation': {'en': "Kosovo's privatisation process is under scrutiny",
  'tr': "Kosova'nın özelleştirme süreci büyüteç altında"}}

In [8]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-tr-en")
model = AutoModelForSeq2SeqLM.from_pretrained("Helsinki-NLP/opus-mt-tr-en")

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.38k [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/840k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/797k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.56M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/models/marian/tokenization_marian.py:175: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")
/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


pytorch_model.bin:   0%|          | 0.00/307M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

In [9]:
model

MarianMTModel(
  (model): MarianModel(
    (shared): Embedding(62389, 512, padding_idx=62388)
    (encoder): MarianEncoder(
      (embed_tokens): Embedding(62389, 512, padding_idx=62388)
      (embed_positions): MarianSinusoidalPositionalEmbedding(512, 512)
      (layers): ModuleList(
        (0-5): 6 x MarianEncoderLayer(
          (self_attn): MarianAttention(
            (k_proj): Linear(in_features=512, out_features=512, bias=True)
            (v_proj): Linear(in_features=512, out_features=512, bias=True)
            (q_proj): Linear(in_features=512, out_features=512, bias=True)
            (out_proj): Linear(in_features=512, out_features=512, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
          (activation_fn): SiLU()
          (fc1): Linear(in_features=512, out_features=2048, bias=True)
          (fc2): Linear(in_features=2048, out_features=512, bias=True)
          (final_layer_norm): LayerNorm((512,), eps=1e-05

In [10]:
# https://huggingface.co/docs/transformers/model_doc/marian

In [11]:
def generate_translation(src_text, max_length = 50):

  # Tokenize input
  encoder_inputs = tokenizer(src_text, return_tensors="pt")

  # intializes the decoder input with decoder start token
  decoder_input = torch.tensor([[model.config.decoder_start_token_id]])

  # change the model to eval mode.
  model.eval()
  with torch.no_grad():

    generated_tokens = []

    while len(generated_tokens) < max_length:

      outputs = model(
          input_ids=encoder_inputs.input_ids,
          attention_mask=encoder_inputs.attention_mask,
          decoder_input_ids=decoder_input
      )


      next_token_logits = outputs.logits[:, -1, :]


      # get the token with maximum logits value
      next_token = torch.argmax(next_token_logits, dim=-1)

      generated_tokens.append(next_token.item())

      if next_token.item() == tokenizer.eos_token_id:
          break
      print(decoder_input)
      decoder_input = torch.cat([decoder_input, next_token.unsqueeze(0)], dim=1)
      print(decoder_input)
    translated_text = tokenizer.decode(generated_tokens, skip_special_tokens=True)
  return translated_text


In [12]:

### print("\nStep by step generation:")
# for i in range(len(generated_tokens)):
#     partial_text = tokenizer.decode(generated_tokens[:i+1], skip_special_tokens=True)
#     print(f"Step {i+1}: {partial_text}")

In [13]:
model.config.num_beams

6

In [14]:
print(generate_translation(ds['validation'][1]['translation']['tr']))

tensor([[62388]])
tensor([[62388, 31058]])
tensor([[62388, 31058]])
tensor([[62388, 31058,     4]])
tensor([[62388, 31058,     4]])
tensor([[62388, 31058,     4,     8]])
tensor([[62388, 31058,     4,     8]])
tensor([[62388, 31058,     4,     8,  1129]])
tensor([[62388, 31058,     4,     8,  1129]])
tensor([[62388, 31058,     4,     8,  1129,  1782]])
tensor([[62388, 31058,     4,     8,  1129,  1782]])
tensor([[62388, 31058,     4,     8,  1129,  1782,   206]])
tensor([[62388, 31058,     4,     8,  1129,  1782,   206]])
tensor([[62388, 31058,     4,     8,  1129,  1782,   206,  3094]])
tensor([[62388, 31058,     4,     8,  1129,  1782,   206,  3094]])
tensor([[62388, 31058,     4,     8,  1129,  1782,   206,  3094,     9]])
tensor([[62388, 31058,     4,     8,  1129,  1782,   206,  3094,     9]])
tensor([[62388, 31058,     4,     8,  1129,  1782,   206,  3094,     9, 11363]])
tensor([[62388, 31058,     4,     8,  1129,  1782,   206,  3094,     9, 11363]])
tensor([[62388, 31058,     4

In [15]:
ds["validation"][1]["translation"]["tr"]

"Norveç'in beş milyon insanı en yüksek yaşam standartlarının tadını çıkarıyor, sadece Avrupa'da değil, dünyada."

In [16]:
ds["validation"][1]["translation"]["en"]

"Norway's five million people enjoy one of the highest standards of living, not just in Europe, but in the world."

In [17]:
# reference to get the python file from github



https://colab.research.google.com/github/jckantor/cbe61622/blob/master/docs/A.02-Downloading_Python_source_files_from_github.ipynb

In [18]:
# get constraints

user = "vvikasreddy"
repo = "lexically_constrained_beam_search_"
pyfile = "constraints.py"

# url = "https://github.com/vvikasreddy/lexically_constrained_beam_search_/blob/main/constraints.py"
url = f"https://raw.githubusercontent.com/{user}/{repo}/main/{pyfile}"
!wget --no-cache --backups=1 {url}

import constraints

--2024-11-03 13:02:12--  https://raw.githubusercontent.com/vvikasreddy/lexically_constrained_beam_search_/main/constraints.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4406 (4.3K) [text/plain]
Failed to rename constraints.py to constraints.py.1: (2) No such file or directory
Saving to: ‘constraints.py’

constraints.py      100%[===================>]   4.30K  --.-KB/s    in 0s      

2024-11-03 13:02:12 (58.7 MB/s) - ‘constraints.py’ saved [4406/4406]



In [19]:
# takes nice 5 minutes to get all the constraints of length 2
c = constraints.get_constraints()

In [53]:
def generate_translation(src_text, decoder_input = [],  max_length = 1):

  """generate the decoder input ids and corresponding probabilities"""


  # Tokenize input
  encoder_inputs = tokenizer(src_text, return_tensors="pt")


  # initialize if not initialized.
  if not decoder_input:
    # because the intial decoder start token has probabilitty 1
    probabilities = torch.tensor([[1]])
    decoder_input = torch.tensor([[model.config.decoder_start_token_id]])

  # change the model to eval mode.
  model.eval()
  with torch.no_grad():

    generated_tokens = []

    outputs = model(
        input_ids=encoder_inputs.input_ids,
        attention_mask=encoder_inputs.attention_mask,
        decoder_input_ids=decoder_input
    )

    next_token_logits = outputs.logits[:, -1, :]

    next_token = torch.argmax(next_token_logits, dim=-1)


    top_probs, top_indices = torch.topk(torch.softmax(next_token_logits, dim=-1), k = 5)


  decoder_inputs = []
  probs = []
  # to visualize data
  vis_data = []
  for indx, id in enumerate(top_indices[0]):
    # print(decoder_input, id.unsqueeze(0).unsqueeze(0), id, "jhere")
    # print(probabilities, top_probs[0][indx].unsqueeze(0).unsqueeze(0))
    decoder_inputs.append(torch.cat([decoder_input, id.unsqueeze(0).unsqueeze(0)], dim=1))
    probs.append(torch.cat([probabilities, top_probs[0][indx].unsqueeze(0).unsqueeze(0)], dim=1))
    # print(decoder_inputs[indx], indx)
    vis_data.append((vis_data, tokenizer.decode(decoder_inputs[indx].squeeze(), skip_special_tokens = True)))
  # translated_text = tokenizer.decode(generated_tokens, skip_special_tokens=True)
  # print(decoder_iputs, probs)
  # print(vis_data)
  return decoder_inputs, probs, vis_data
  # return decoder_input, probabilities


In [62]:
print(generate_translation(ds['validation'][1]['translation']['tr']))
c

([tensor([[62388, 31058]]), tensor([[62388,  3884]]), tensor([[62388,  1014]]), tensor([[62388,    71]]), tensor([[62388, 36600]])], [tensor([[1.0000, 0.4112]]), tensor([[1.0000, 0.1607]]), tensor([[1.0000, 0.0560]]), tensor([[1.0000, 0.0387]]), tensor([[1.0000, 0.0166]])], [([...], 'Norway'), ([...], 'Five'), ([...], '5'), ([...], 'The'), ([...], 'Norwegian')])


{('Southeast', 'European'): (('Southeast', 'European'), 2.007429209652565),
 ('European', 'Times'): (('European', 'Times'), 1.9167591854827242),
 ('Times', 'için'): (('for', 'Southeast'), 1.8911110573345382),
 ('için', "Priştine'den"): (('in', 'Pristina'), 0.9216987197497427),
 ('haberi', '--'): (('for', 'Southeast'), 1.3272785799552846),
 ("SETimes'a", 'konuşan'): (('told', 'SETimes.'), 0.9561859994381473),
 ('için', "Üsküp'ten"): (('in', 'Skopje'), 0.9333156901837453),
 ("SETimes'a", 'verdiği'): (('told', 'SETimes.'), 0.9616320325311761),
 ('verdiği', 'demeçte,'): (('told', 'SETimes.'), 0.9982304560834028),
 ('Salı', 'günü'): (('on', 'Tuesday'), 1.1367580877880021),
 ('Dışişleri', 'Bakanı'): (('Foreign', 'Minister'), 1.370151811801477),
 ('Hırvatistan', 've'): (('Croatia', 'and'), 0.9307553543356438),
 ('yanı', 'sıra'): (('well', 'as'), 1.3045270862505716),
 ('AB', 've'): (('EU', 'and'), 1.0022170935178725),
 ('[Getty', 'Images]'): (('[Getty', 'Images]'), 1.5597082338725858),
 ('ve',

In [70]:
def get_ngrams(src, n = 2, ):
  src = src.split(" ")

  src = [tuple(src[i:i+n]) for i in range(len(src) - n + 1)]

  return src

def constraints_tokens(src, c):
  ngrams = get_ngrams(src)
  constraints_src = []
  for ngram in ngrams:
    # print(ngram)
    if ngram in c:
      for gram in ngram:

        constraints_src.append(tokenizer(gram, return_tensors="pt"))
  return constraints_src

In [73]:
x = constraints_tokens(ds['validation'][1]['translation']['tr'] + ' Times' +  ' için', c)
# c
x

[{'input_ids': tensor([[3762,    0]]), 'attention_mask': tensor([[1, 1]])},
 {'input_ids': tensor([[37,  0]]), 'attention_mask': tensor([[1, 1]])}]

In [55]:
def beam_search(maxlen, numC, k, src):

    grids = [[[0 for _ in range(k)] for _ in range(numC)] for _ in range(maxlen)]
    # should the below be the size
    # grids = [[[] for _ in range(numC)] for _ in range(maxlen)]

    # intialize the first grid to start hyp
    for i in range(k):
        grids[0][0][i] = 'start'

    print(grids)
    grids[0][0]

    for t in range(1, maxlen):

        index_c = max(0, (numC - t) - maxlen)

        for c in range(index_c, min(t, numC) + 1):

            s = []
            g = []

            for element in grids[t-1][c]:
                # if element == 'start':
                # guess ther is no need for conditioning, just generate.
                g, probs, vis_data = generate_translation(src_text= src, decoder_input = [])

            # retrieve the  probability of the constraint and add that. to the decoder_input.
            if c > 0:
              for element in grids[t-1][c-1]:

                # get the constraints store them
                # cons = # some constraints # add based on c value. cons = [c]
                # s, probs, vis_data = generate_translation(src_text= src, decoder_input = [cons])


            # combine g and s properly and get the top k values.
            # grid[t][c] = argmax(g | s)

            print(g)
            print(probs)

            print(vis_data)
            print(len(g[0]))

            break
        break

    # sanity : print grids
    print(grids)


beam_search(maxlen= 4, numC=2, k = 5, src = ds["train"][1]["translation"]["tr"])

[[['start', 'start', 'start', 'start', 'start'], [0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]]
[tensor([[62388,  1969]]), tensor([[62388,   323]]), tensor([[62388,    67]]), tensor([[62388,  1132]]), tensor([[62388,   626]])]
[tensor([[1.0000, 0.8746]]), tensor([[1.0000, 0.0156]]), tensor([[1.0000, 0.0114]]), tensor([[1.0000, 0.0039]]), tensor([[1.0000, 0.0038]])]
[([...], 'Kos'), ([...], 'In'), ([...], 'He'), ([...], 'With'), ([...], 'As')]
1
[[['start', 'start', 'start', 'start', 'start'], [0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]]
